# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba46b486d368af7531f0030909f137a62c4e924c29f5bceba2c2fdf63d86bca144164ec1e6da23d1349e80620486d6f1b46e3a2574fdc1f6d14ce6f274598e56

test:
  secret_key_base: ea663d14e42ab69de7d1f7989a58542b140ac4fc37b2852ceea85ddca61d6ae346a5aeee018f1d1e842fb9a6e410b35cceb7036c09a6f563dc3b9310e7d9113e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
